version: '3.7'
services:
  document_generation_db:
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3349:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_DATABASE: generator
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - ./docker/.db/:/var/lib/mysql/
    networks:
      - jarvis
  document_generation_php:
    build: docker/dev/php-fpm
    volumes:
      - ./:/var/www/symfony
      - ~/.ssh:/root/.ssh
    links:
      - document_generation_db
    networks:
      - jarvis
  document_generation_nginx:
    build: docker/dev/nginx
    ports:
      - "8081:80"
    links:
      - document_generation_php
    volumes:
      - ./:/var/www/symfony
      - ./docker/logs:/var/log/nginx/
    networks:
      - jarvis
networks:
  jarvis:
    external: true